scrape_configs:
  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: locust-exporter
    scrape_interval: 10s
    static_configs:
      - targets:
          - locust-exporter:9646