apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: benchy-monitor
  namespace: monitoring
  labels:
    app: benchy
    app.kubernetes.io/part-of: kube-prometheus
spec:
  selector:
    matchLabels:
      app: benchy
  endpoints:
    - port: metrics
      interval: 15s


