apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      restartPolicy: Always
      #TODO add initContainer waiting benchy ready
      containers:
        - name: load-generator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: quay.io/massigollo/benchy:load
          env:
            - name: USERS
              value: "10"
            - name: TARGET_ADDR
              value: "benchy:8080"
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi