---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator-exporter
  labels:
    app: loadgenerator
spec:
  selector:
    app: loadgenerator
  ports:
    - name: metrics
      port: 9646
      targetPort: 9646
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loadgenerator-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: loadgenerator
  endpoints:
    - port: metrics
      interval: 15s  # the scrape interval
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      restartPolicy: Always
      #TODO add initContainer waiting benchy ready
      containers:
        - name: locust-exporter
          image: containersol/locust_exporter
          imagePullPolicy: Always
          env:
            - name: LOCUST_HOST
              value: "localhost"
          ports:
            - containerPort: 9646
        - name: load-generator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: quay.io/massigollo/benchy:load
          imagePullPolicy: Always
          env:
            - name: USERS
              value: "10"
            - name: TARGET_ADDR
              value: "benchy:8080"
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8089