---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: locust-exporter-monitor
spec:
  selector:
    matchLabels:
      app: loadgenerator
  endpoints:
    - port: metrics
      interval: 15s  # the scrape interval