services:

  benchy:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OTLP_ENDPOINT=otel-collector:4317
    command:
      - server

#  kafka:
#    extends:
#      file: docker-compose.kafka.yaml
#      service: kafka

#  zookeeper:
#    extends:
#      file: docker-compose.kafka.yaml
#      service: zookeeper

